# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='CategoryNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
            options={
                'verbose_name_plural': 'Category Notifications',
                'verbose_name': 'Category Notification',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'verbose_name': 'Institution',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Institution')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'verbose_name': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('begin', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
            ],
            options={
                'verbose_name_plural': 'Performances',
                'verbose_name': 'Performance',
            },
        ),
        migrations.CreateModel(
            name='PerformanceNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Performance')),
            ],
            options={
                'verbose_name_plural': 'Performance Notifications',
                'verbose_name': 'Performance Notification',
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'User Emails',
                'verbose_name': 'User Email',
            },
        ),
        migrations.AddField(
            model_name='performancenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserEmail'),
        ),
        migrations.AddField(
            model_name='categorynotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserEmail'),
        ),
        migrations.AddField(
            model_name='category',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Institution'),
        ),
        migrations.AlterUniqueTogether(
            name='performancenotification',
            unique_together=set([('user', 'performance')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorynotification',
            unique_together=set([('user', 'category')]),
        ),
    ]
