# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynotification',
            name='user',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='performancenotification',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
