# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161124_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynotification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='categorynotification',
            unique_together=set([('user', 'device', 'category', 'verified')]),
        ),
    ]
