# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161113_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='verification_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
