# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161113_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremail',
            options={'verbose_name': 'User Email', 'verbose_name_plural': 'User Emails'},
        ),
    ]
