# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161124_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='verification_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
