# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161124_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='eventid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
