---
- hosts: theaterwecker
  become: true

  tasks:
  - name: update packages cache
    apt: update_cache=yes cache_valid_time=3600

  - name: install packages
    apt: name={{ item.name }}
    with_items:
      - { name: 'nginx' }
      - { name: 'php-fpm' }

  - name: create theater wecker data dir
    file: path=/var/data/theaterwecker/ state=directory mode=0755 owner=www-data group=www-data

  - name: create nginx config
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
    notify:
      - reload nginx

  - name: checkout files
    git: repo=https://github.com/codeforchemnitz/theaterwecker.git dest=/var/www/theaterwecker
    
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
